INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Barrett', 'Senator', 'Third Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Brady', 'Senator', 'Second Plymouth and Norfolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('William Brownsberger', 'Senator', 'Suffolk and Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Nick Collins', 'Senator', 'First Suffolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Joanne Comerford', 'Senator', 'Hampshire, Franklin and Worcester', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Cynthia Creem', 'Senator', 'Norfolk and Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Brendan Crighton', 'Senator', 'Third Essex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Cronin', 'Senator', 'Worcester and Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Julian Cyr', 'Senator', 'Cape and Islands', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Sal DiDomenico', 'Senator', 'Middlesex and Suffolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kelly Dooner', 'Senator', 'Third Bristol and Plymouth', 'Republican', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('William Driscoll', 'Senator', 'Norfolk, Plymouth and Bristol', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Peter Durant', 'Senator', 'Worcester and Hampshire', 'Republican', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Lydia Edwards', 'Senator', 'Third Suffolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('James Eldridge', 'Senator', 'Middlesex and Worcester', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Ryan Fattman', 'Senator', 'Worcester and Hampden', 'Republican', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Paul Feeney', 'Senator', 'Bristol and Norfolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Dylan Fernandes', 'Senator', 'Plymouth and Barnstable', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Barry Finegold', 'Senator', 'Second Essex and Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Cindy Friedman', 'Senator', 'Fourth Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Adam Gómez', 'Senator', 'Hampden', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Patricia Jehlen', 'Senator', 'Second Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Keenan', 'Senator', 'Norfolk and Plymouth', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Edward Kennedy', 'Senator', 'First Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Robyn Kennedy', 'Senator', 'First Worcester', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jason Lewis', 'Senator', 'Fifth Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Joan Lovely', 'Senator', 'Second Essex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Paul Mark', 'Senator', 'Berkshire, Hampden, Franklin and Hampshire', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Liz Miranda', 'Senator', 'Second Suffolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Mark Montigny', 'Senator', 'Second Bristol and Plymouth', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Moore', 'Senator', 'Second Worcester', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Patrick O''Connor', 'Senator', 'First Plymouth and Norfolk', 'Republican', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jacob Oliveira', 'Senator', 'Hampden, Hampshire and Worcester', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Pavel Payano', 'Senator', 'First Essex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Rebecca Rausch', 'Senator', 'Norfolk, Worcester and Middlesex', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Rodrigues', 'Senator', 'First Bristol and Plymouth', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Rush', 'Senator', 'Norfolk and Suffolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Karen Spilka', 'Senator', 'Middlesex and Norfolk', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Bruce Tarr', 'Senator', 'First Essex and Middlesex', 'Republican', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Velis', 'Senator', 'Hampden and Hampshire', 'Democrat', 'Senate');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('James Arciero', 'Representative', '2nd Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('James Arena-DeRosa', 'Representative', '8th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jennifer Balinsky Armini', 'Representative', '8th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Shirley Arriaga', 'Representative', '8th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Brian Ashe', 'Representative', '2nd Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Bruce Ayers', 'Representative', '1st Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michelle Badger', 'Representative', '1st Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Christine Barber', 'Representative', '34th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Barrett', 'Representative', '1st Berkshire', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Donald Berthiaume', 'Representative', '5th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David Biele', 'Representative', '4th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Natalie Blais', 'Representative', '1st Franklin', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Nicholas Boldyga', 'Representative', '3rd Hampden', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Hannah Bowen', 'Representative', '6th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Antonio Cabral', 'Representative', '13th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Daniel Cahill', 'Representative', '10th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Simon Cataldo', 'Representative', '14th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Chaisson', 'Representative', '1st Bristol', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Tackey Chan', 'Representative', '2nd Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michelle Ciccolo', 'Representative', '15th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Mike Connolly', 'Representative', '26th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Rob Consalvo', 'Representative', '14th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Manny Cruz', 'Representative', '7th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Mark Cusack', 'Representative', '5th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Leigh Davis', 'Representative', '3rd Berkshire', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Day', 'Representative', '31st Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Marjorie Decker', 'Representative', '25th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David DeCoste', 'Representative', '5th Plymouth', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kip Diggs', 'Representative', '2nd Barnstable', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Mindy Domb', 'Representative', '3rd Hampshire', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kate Donaghue', 'Representative', '19th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Daniel Donahue', 'Representative', '16th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Paul Donato', 'Representative', '35th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michelle DuBois', 'Representative', '10th Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Patricia Duffy', 'Representative', '5th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Rodney Elliott', 'Representative', '16th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Tricia Farley-Bouvier', 'Representative', '2nd Berkshire', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kimberly Ferguson', 'Representative', '1st Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Ann-Margaret Ferrante', 'Representative', '5th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Lisa Field', 'Representative', '3rd Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Finn', 'Representative', '6th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Carole Fiola', 'Representative', '6th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Christopher Flanagan', 'Representative', '1st Barnstable', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Brandy Fluker-Reid', 'Representative', '12th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Paul Frost', 'Representative', '7th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Dennis Gallagher', 'Representative', '8th Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('William Galvin', 'Representative', '6th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Sean Garballey', 'Representative', '23rd Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Judith Garcia', 'Representative', '11th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Colleen Garry', 'Representative', '36th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Gaskey', 'Representative', '2nd Plymouth', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Carmine Gentile', 'Representative', '13th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jessica Giannino', 'Representative', '16th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Homar Gómez', 'Representative', '2nd Hampshire', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Carlos González', 'Representative', '10th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kenneth Gordon', 'Representative', '21st Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Danielle Gregoire', 'Representative', '4th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Richard Haggerty', 'Representative', '30th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Ryan Hamilton', 'Representative', '15th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('James Hawkins', 'Representative', '2nd Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Christopher Hendricks', 'Representative', '11th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Natalie Higgins', 'Representative', '4th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kate Hogan', 'Representative', '3rd Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Russell Holmes', 'Representative', '6th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kevin Honan', 'Representative', '17th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Tara Hong', 'Representative', '18th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Vanna Howard', 'Representative', '17th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Steven Howitt', 'Representative', '4th Bristol', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Daniel Hunt', 'Representative', '13th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Bradley Jones', 'Representative', '20th Middlesex', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Hannah Kane', 'Representative', '11th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kristin Kassner', 'Representative', '2nd Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Patrick Kearney', 'Representative', '4th Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Mary Keefe', 'Representative', '15th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Sally Kerans', 'Representative', '13th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Meghan Kilcoyne', 'Representative', '12th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Kushmerek', 'Representative', '3rd Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kathleen LaNatra', 'Representative', '12th Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Lawn', 'Representative', '10th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David LeBoeuf', 'Representative', '17th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jack Lewis', 'Representative', '7th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David Linsky', 'Representative', '5th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kate Lipper-Garabedian', 'Representative', '32nd Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jay Livingstone', 'Representative', '8th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Marc Lombardo', 'Representative', '22nd Middlesex', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Hadley Luddy', 'Representative', '4th Barnstable', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('William MacGregor', 'Representative', '10th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Adrian Madaro', 'Representative', '1st Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Mahoney', 'Representative', '13th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Ronald Mariano', 'Representative', '3rd Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Christopher Markey', 'Representative', '9th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Marsi', 'Representative', '6th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Joseph McGonagle', 'Representative', '28th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Joseph McKenna', 'Representative', '18th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Paul McMurtry', 'Representative', '11th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Rita Mendes', 'Representative', '11th Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Joan Meschino', 'Representative', '3rd Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Aaron Michlewitz', 'Representative', '3rd Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Thomas Moakley', 'Representative', 'Barnstable, Dukes and Nantucket', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Samantha Montaño', 'Representative', '15th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Frank Moran', 'Representative', '17th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Moran', 'Representative', '9th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Moran', 'Representative', '18th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David Muradian', 'Representative', '9th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('James Murphy', 'Representative', '4th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Brian Murray', 'Representative', '10th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Tram Nguyen', 'Representative', '18th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('James O''Day', 'Representative', '14th Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Norman Orrall', 'Representative', '12th Bristol', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Steven Ouellette', 'Representative', '8th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Steven Owens', 'Representative', '29th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Francisco Paulino', 'Representative', '16th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kelly Pease', 'Representative', '4th Hampden', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Alice Peisch', 'Representative', '14th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Edward Philips', 'Representative', '8th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Bridget Plouffe', 'Representative', '9th Plymouth', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Angelo Puppolo', 'Representative', '12th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Adrianne Ramos', 'Representative', '14th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Orlando Ramos', 'Representative', '9th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Sean Reid', 'Representative', '11th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Estela Reyes', 'Representative', '4th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David Robertson', 'Representative', '19th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David Rogers', 'Representative', '24th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('John Rogers', 'Representative', '12th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jeffrey Roy', 'Representative', '10th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Daniel Ryan', 'Representative', '2nd Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Lindsay Sabadosa', 'Representative', '1st Hampshire', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Amy Sangiolo', 'Representative', '11th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Aaron Saunders', 'Representative', '7th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Adam Scanlon', 'Representative', '14th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Margaret Scarsdale', 'Representative', '1st Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Greg Schwartz', 'Representative', '12th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Danillo Sena', 'Representative', '37th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Dawne Shand', 'Representative', '1st Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Alan Silvia', 'Representative', '7th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Todd Smola', 'Representative', '1st Hampden', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Michael Soter', 'Representative', '8th Worcester', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Priscila Sousa', 'Representative', '6th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Thomas Stanley', 'Representative', '9th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Alyson Sullivan-Almeida', 'Representative', '7th Plymouth', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kenneth Sweezey', 'Representative', '6th Plymouth', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Mark Sylvia', 'Representative', '10th Bristol', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Joshua Tarsky', 'Representative', '13th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Justin Thurber', 'Representative', '5th Bristol', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jeffrey Turco', 'Representative', '19th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Chynah Tyler', 'Representative', '7th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Steven Ultrino', 'Representative', '33rd Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Erika Uyterhoeven', 'Representative', '27th Middlesex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Andres Vargas', 'Representative', '3rd Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Marcus Vaughn', 'Representative', '9th Norfolk', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('David Vieira', 'Representative', '3rd Barnstable', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Tommy Vitolo', 'Representative', '15th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Thomas Walsh', 'Representative', '12th Essex', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Richard Wells', 'Representative', '7th Norfolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Susannah Whipps', 'Representative', '2nd Franklin', 'Unenrolled', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Bud Williams', 'Representative', '11th Hampden', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Donald Wong', 'Representative', '9th Essex', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Christopher Worrell', 'Representative', '5th Suffolk', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Steven Xiarhos', 'Representative', '5th Barnstable', 'Republican', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Jonathan Zlotnik', 'Representative', '2nd Worcester', 'Democrat', 'House');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('William Francis Galvin', 'Secretary of the Commonwealth of Massachusetts', NULL, NULL, 'Executive');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Maura Healey', 'Governor of Massachusetts', NULL, NULL, 'Executive');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Kim Driscoll', 'Lieutenant Governor of Massachusetts', NULL, NULL, 'Executive');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Andrea Joy Campbell', 'Attorney General', NULL, NULL, 'Executive');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Deborah (Deb) B. Goldberg', 'Treasurer and Receiver-General', NULL, NULL, 'Executive');
INSERT INTO elected_officials (full_name, title, district, party, body) VALUES ('Diana DiZoglio', 'State Auditor', NULL, NULL, 'Executive');
